version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignored_updates:
      # Hypotehsis is only used for testing and is updated quite often
      - match:
          dependency_name: hypothesis
