name: PR testing

on: [pull_request]

jobs:
  lint-custom:
    runs-on: ubuntu-latest
    container: jesserockz/esphome-lint
    name: Lint Custom
    steps:
    - uses: actions/checkout@v2
    - run: script/setup
    - run: script/ci-custom.py
  lint-python:
    runs-on: ubuntu-latest
    container: jesserockz/esphome-lint
    name: Lint Python
    steps:
    - uses: actions/checkout@v2
    - run: script/setup
    - run: script/lint-python
  lint-tidy:
    runs-on: ubuntu-latest
    container: jesserockz/esphome-lint
    name: Lint Tidy
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: script/setup
    - run: pio init --ide atom
    - run: script/clang-tidy --all-headers --fix
    - run: script/ci-suggest-changes
  lint-format:
    runs-on: ubuntu-latest
    container: jesserockz/esphome-lint
    name: Lint Format
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: script/setup
    - run: script/clang-format -i
    - run: script/ci-suggest-changes

  test:
    runs-on: ubuntu-latest
    container: jesserockz/esphome-lint
    strategy:
      matrix:
        test:
        - test1
        - test2
        - test3
        - test4
    steps:
    - uses: actions/checkout@v2
    - run: script/setup
    - run: esphome tests/${{ matrix.test }}.yaml compile
